server:
    port: 8080

spring:
    main:
        banner-mode: off

    datasource:
        url: jdbc:mysql://localhost:3306/bank
        username: root
        password: 123123

    jpa:
        hibernate:
            ddl-auto: create